<?php
namespace App\Services\Inventory;
use App\Models\Inventory\{InventoryItem,InventoryStock,InventoryReallocationSuggestion,InventoryWarehouse};
use Illuminate\Support\Collection;
class ReallocationService {
 public function suggest(?int $itemId=null): Collection { $items=InventoryItem::where('is_active',1)->when($itemId,fn($q)=>$q->whereKey($itemId))->get();$warehouses=InventoryWarehouse::where('status','active')->get();$out=collect();foreach($items as $item){$stocks=InventoryStock::where('item_id',$item->id)->get()->keyBy('warehouse_id');$sources=[];$targets=[];foreach($warehouses as $w){$st=$stocks->get($w->id);$avail=$st?$st->available():0;$surplus=max(0,$avail-(float)$item->minimum_stock);$shortage=max(0,(float)$item->reorder_level-$avail);if($surplus>0)$sources[]=['w'=>$w,'q'=>$surplus];if($shortage>0)$targets[]=['w'=>$w,'q'=>$shortage];}foreach($targets as $t){foreach($sources as &$src){if($t['q']<=0)break;if($src['q']<=0||$src['w']->id===$t['w']->id)continue;$move=min($src['q'],$t['q']);$distance=$this->distance($src['w'],$t['w']);$out->push(['item_id'=>$item->id,'from_warehouse_id'=>$src['w']->id,'to_warehouse_id'=>$t['w']->id,'suggested_quantity'=>$move,'from_surplus'=>$src['q'],'to_shortage'=>$t['q'],'distance_km'=>$distance,'priority_score'=>($t['q']*100)-(($distance??0)*2)]);$src['q']-=$move;$t['q']-=$move;}}}return $out->sortByDesc('priority_score')->values();}
 public function generate():int { InventoryReallocationSuggestion::where('status','proposed')->update(['status'=>'superseded']);$n=0;foreach($this->suggest() as $s){InventoryReallocationSuggestion::create($s+['status'=>'proposed','created_by_account_id'=>session('administrative_account_id')??auth()->id(),'reason_ar'=>'اقتراح آلي بناءً على الفائض والعجز والمسافة','reason_en'=>'Automatic suggestion based on surplus, shortage and distance']);$n++;}return $n;}
 private function distance(InventoryWarehouse $a,InventoryWarehouse $b):?float{if($a->latitude===null||$a->longitude===null||$b->latitude===null||$b->longitude===null)return null;$r=6371;$dLat=deg2rad($b->latitude-$a->latitude);$dLon=deg2rad($b->longitude-$a->longitude);$x=sin($dLat/2)**2+cos(deg2rad($a->latitude))*cos(deg2rad($b->latitude))*sin($dLon/2)**2;return round($r*2*asin(min(1,sqrt($x))),2);}
}
