<?php

declare(strict_types=1);

namespace App\Http\Controllers\Staff;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Symfony\Component\HttpFoundation\BinaryFileResponse;

/**
 * Serves report Excel files generated by staff Livewire report components.
 *
 * SECURITY model:
 *  1. The Livewire export action stores a report_exports row and encrypts its ID
 *     using Laravel's AES encrypt(), placing it in the download URL query string.
 *  2. This controller decrypts the ID, looks up the row, and verifies that the
 *     requesting staff account matches the one that created the export.
 *  3. The file path is taken from the trusted report_exports row — never from
 *     the request directly — preventing path traversal and cross-user access.
 *  4. Each export gets a UUID-scoped path so files cannot collide or be
 *     guessed by another authenticated user.
 */
class ReportDownloadController extends Controller
{
    public function __invoke(Request $request): BinaryFileResponse
    {
        $accountId = auth('staff')->id();
        abort_if(! $accountId, 403);

        $encryptedId = $request->query('export');
        abort_if(! $encryptedId, 400);

        $exportId = decrypt($encryptedId);

        $record = DB::table('report_exports')
            ->where('id', (int) $exportId)
            ->where('actor_type', 'staff')
            ->where('actor_account_id', (int) $accountId)
            ->first();

        abort_if(! $record, 403, 'Export record not found or does not belong to this account.');

        $path = $record->file_path;

        abort_if(! $path || ! str_starts_with($path, 'reports/'), 403);
        abort_if(! Storage::disk('local')->exists($path), 404, 'Report file has expired or been removed.');

        $filename = $request->query('name') ?: basename($path);

        return response()->download(Storage::disk('local')->path($path), $filename, [
            'Content-Type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'Content-Disposition' => 'attachment; filename="'.rawurlencode($filename).'"',
        ]);
    }
}
