<?php

declare(strict_types=1);

namespace Modules\Reporting\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Inserts or refreshes all 21 report definition rows.
 *
 * Safe to run multiple times — uses upsert keyed on `code`.
 */
final class ReportDefinitionSeeder extends Seeder
{
    public function run(): void
    {
        $now = now()->toDateTimeString();

        $definitions = [
            [
                'code' => 'student_registry',
                'name_ar' => 'سجل الطلاب',
                'name_en' => 'Student Registry',
                'description_ar' => 'قائمة كاملة بملفات الطلاب مع بيانات التسجيل الأساسية.',
                'description_en' => 'Full list of student profiles with basic registration data.',
                'report_family' => 'registry',
                'filter_schema' => json_encode(['institution_semester_id', 'class_group_id']),
                'permission_key' => 'student.view',
                'organization_scope_allowed' => false,
                'admin_only' => false,
            ],
            [
                'code' => 'enrollment_placement',
                'name_ar' => 'التحصيل الدراسي والتوزيع',
                'name_en' => 'Enrolment & Placement',
                'description_ar' => 'توزيع الطلاب على المجموعات الدراسية والمستويات الأكاديمية.',
                'description_en' => 'Student placement across class groups and academic levels.',
                'report_family' => 'registry',
                'filter_schema' => json_encode(['institution_semester_id', 'class_group_id']),
                'permission_key' => 'enrollment.view',
                'organization_scope_allowed' => false,
                'admin_only' => false,
            ],
            [
                'code' => 'student_transfers',
                'name_ar' => 'تحويلات الطلاب',
                'name_en' => 'Student Transfers',
                'description_ar' => 'سجل عمليات تحويل الطلاب بين المؤسسات التعليمية.',
                'description_en' => 'Record of student transfer operations between institutions.',
                'report_family' => 'registry',
                'filter_schema' => json_encode(['institution_semester_id', 'date_from', 'date_to']),
                'permission_key' => 'enrollment.view',
                'organization_scope_allowed' => false,
                'admin_only' => false,
            ],
            [
                'code' => 'student_attendance',
                'name_ar' => 'حضور الطلاب',
                'name_en' => 'Student Attendance',
                'description_ar' => 'سجلات الحضور اليومي للطلاب مع الحالة والسبب.',
                'description_en' => 'Daily student attendance records with status and reason.',
                'report_family' => 'attendance',
                'filter_schema' => json_encode(['institution_semester_id', 'class_group_id', 'operational_period_id', 'date_from', 'date_to']),
                'permission_key' => 'attendance_report.read',
                'organization_scope_allowed' => false,
                'admin_only' => false,
            ],
            [
                'code' => 'staff_attendance',
                'name_ar' => 'حضور الموظفين',
                'name_en' => 'Staff Attendance',
                'description_ar' => 'سجلات حضور الموظفين وتوقيت وصولهم.',
                'description_en' => 'Staff attendance records with arrival confirmation times.',
                'report_family' => 'attendance',
                'filter_schema' => json_encode(['institution_semester_id', 'operational_period_id', 'date_from', 'date_to']),
                'permission_key' => 'attendance_report.read',
                'organization_scope_allowed' => false,
                'admin_only' => false,
            ],
            [
                'code' => 'assessments_marks',
                'name_ar' => 'الاختبارات والدرجات',
                'name_en' => 'Assessments & Marks',
                'description_ar' => 'درجات الطلاب في كافة الاختبارات والمواد الدراسية.',
                'description_en' => 'Student scores across all assessments and subjects.',
                'report_family' => 'marks',
                'filter_schema' => json_encode(['institution_semester_id', 'class_group_id']),
                'permission_key' => 'result_report.read',
                'organization_scope_allowed' => false,
                'admin_only' => false,
            ],
            [
                'code' => 'published_results',
                'name_ar' => 'النتائج المنشورة',
                'name_en' => 'Published Results',
                'description_ar' => 'النتائج الرسمية المنشورة للطلاب مع الترتيب النهائي.',
                'description_en' => 'Official published results with rankings.',
                'report_family' => 'marks',
                'filter_schema' => json_encode(['institution_semester_id', 'class_group_id']),
                'permission_key' => 'result_report.read',
                'organization_scope_allowed' => false,
                'admin_only' => false,
            ],
            [
                'code' => 'missing_attendance',
                'name_ar' => 'سجلات الحضور الناقصة',
                'name_en' => 'Missing / Incomplete Attendance',
                'description_ar' => 'قوائم الحضور التي لم يتم رفعها أو إرجاعها للتصحيح.',
                'description_en' => 'Attendance sheets not yet submitted or returned for correction.',
                'report_family' => 'compliance',
                'filter_schema' => json_encode(['institution_semester_id', 'class_group_id', 'date_from', 'date_to']),
                'permission_key' => 'attendance_report.read',
                'organization_scope_allowed' => false,
                'admin_only' => false,
            ],
            [
                'code' => 'missing_marks',
                'name_ar' => 'درجات ناقصة',
                'name_en' => 'Missing / Incomplete Marks',
                'description_ar' => 'كشوفات الدرجات التي لم تكتمل أو أُعيدت للتصحيح.',
                'description_en' => 'Mark sheets not yet submitted or returned for correction.',
                'report_family' => 'compliance',
                'filter_schema' => json_encode(['institution_semester_id', 'class_group_id']),
                'permission_key' => 'result_report.read',
                'organization_scope_allowed' => false,
                'admin_only' => false,
            ],
            [
                'code' => 'teaching_assignments',
                'name_ar' => 'تكليفات التدريس',
                'name_en' => 'Teaching Assignments',
                'description_ar' => 'توزيع المعلمين على المواد والمجموعات الدراسية.',
                'description_en' => 'Teacher-subject-class group assignment mapping.',
                'report_family' => 'staff',
                'filter_schema' => json_encode(['institution_semester_id', 'class_group_id']),
                'permission_key' => 'teaching_assignment.manage',
                'organization_scope_allowed' => false,
                'admin_only' => false,
            ],
            [
                'code' => 'staff_positions',
                'name_ar' => 'مناصب الموظفين',
                'name_en' => 'Staff Positions',
                'description_ar' => 'قائمة بمناصب الموظفين الحالية والتاريخية.',
                'description_en' => 'Current and historical staff position assignments.',
                'report_family' => 'staff',
                'filter_schema' => json_encode(['institution_semester_id', 'date_from', 'date_to']),
                'permission_key' => 'staff_profile.view',
                'organization_scope_allowed' => true,
                'admin_only' => false,
            ],
            [
                'code' => 'guardian_relationships',
                'name_ar' => 'علاقات أولياء الأمور',
                'name_en' => 'Guardian Relationships',
                'description_ar' => 'روابط الطلاب بأولياء أمورهم وصلاحيات كل ولي أمر.',
                'description_en' => 'Student-guardian links with authorization levels.',
                'report_family' => 'registry',
                'filter_schema' => json_encode(['institution_semester_id']),
                'permission_key' => 'guardian_relationship.view',
                'organization_scope_allowed' => false,
                'admin_only' => false,
            ],
            [
                'code' => 'correction_requests',
                'name_ar' => 'طلبات التصحيح',
                'name_en' => 'Correction Requests',
                'description_ar' => 'طلبات تصحيح البيانات التي يرفعها أولياء الأمور.',
                'description_en' => 'Data correction requests submitted by guardians.',
                'report_family' => 'requests',
                'filter_schema' => json_encode(['institution_semester_id', 'date_from', 'date_to']),
                'permission_key' => 'correction.review',
                'organization_scope_allowed' => false,
                'admin_only' => false,
            ],
            [
                'code' => 'document_requests',
                'name_ar' => 'طلبات الوثائق',
                'name_en' => 'Document Requests',
                'description_ar' => 'طلبات الوثائق الرسمية المقدمة من قبل الأولياء.',
                'description_en' => 'Official document requests submitted by guardians.',
                'report_family' => 'requests',
                'filter_schema' => json_encode(['institution_semester_id', 'date_from', 'date_to']),
                'permission_key' => 'document.review',
                'organization_scope_allowed' => false,
                'admin_only' => false,
            ],
            [
                'code' => 'issued_documents',
                'name_ar' => 'الوثائق الصادرة',
                'name_en' => 'Issued Documents',
                'description_ar' => 'قائمة بالوثائق الرسمية الصادرة مع أرقامها التسلسلية.',
                'description_en' => 'List of officially issued documents with sequential numbers.',
                'report_family' => 'requests',
                'filter_schema' => json_encode(['institution_semester_id', 'date_from', 'date_to']),
                'permission_key' => 'document.review',
                'organization_scope_allowed' => false,
                'admin_only' => false,
            ],
            [
                'code' => 'formal_requests',
                'name_ar' => 'الطلبات الرسمية المؤسسية',
                'name_en' => 'Formal Institution Requests',
                'description_ar' => 'الطلبات الرسمية المقدمة من المؤسسات إلى الإدارة.',
                'description_en' => 'Formal requests submitted by institutions to management.',
                'report_family' => 'requests',
                'filter_schema' => json_encode(['institution_semester_id', 'date_from', 'date_to']),
                'permission_key' => 'formal_request.respond',
                'organization_scope_allowed' => true,
                'admin_only' => true,
            ],
            [
                'code' => 'audit_activity',
                'name_ar' => 'سجل المراجعة',
                'name_en' => 'Audit Activity',
                'description_ar' => 'سجل كامل بالأحداث والتغييرات على مستوى النظام.',
                'description_en' => 'Full log of system-level events and changes.',
                'report_family' => 'audit',
                'filter_schema' => json_encode(['date_from', 'date_to']),
                'permission_key' => 'audit.view',
                'organization_scope_allowed' => true,
                'admin_only' => true,
            ],
            [
                'code' => 'import_results',
                'name_ar' => 'نتائج الاستيراد',
                'name_en' => 'Import Results',
                'description_ar' => 'تقارير دفعات استيراد البيانات مع النتائج والأخطاء.',
                'description_en' => 'Data import batch reports with outcomes and error counts.',
                'report_family' => 'audit',
                'filter_schema' => json_encode(['institution_semester_id', 'date_from', 'date_to']),
                'permission_key' => 'import.upload',
                'organization_scope_allowed' => false,
                'admin_only' => false,
            ],
            [
                'code' => 'institution_summary',
                'name_ar' => 'ملخص المؤسسات',
                'name_en' => 'Institution Summary',
                'description_ar' => 'نظرة عامة على المؤسسات التعليمية وحالتها.',
                'description_en' => 'Overview of educational institutions and their status.',
                'report_family' => 'audit',
                'filter_schema' => json_encode([]),
                'permission_key' => 'institution.view',
                'organization_scope_allowed' => true,
                'admin_only' => true,
            ],
            [
                'code' => 'notification_events',
                'name_ar' => 'أحداث الإشعارات',
                'name_en' => 'Notification Events',
                'description_ar' => 'سجل إشعارات البوابة والرسائل المرسلة للمستخدمين.',
                'description_en' => 'Portal notification and message delivery log.',
                'report_family' => 'audit',
                'filter_schema' => json_encode(['date_from', 'date_to']),
                'permission_key' => 'audit.view',
                'organization_scope_allowed' => true,
                'admin_only' => true,
            ],
            [
                'code' => 'export_job_history',
                'name_ar' => 'سجل عمليات التصدير',
                'name_en' => 'Export Job History',
                'description_ar' => 'سجل عمليات تصدير التقارير المجدولة والمنجزة.',
                'description_en' => 'History of scheduled and completed report export jobs.',
                'report_family' => 'audit',
                'filter_schema' => json_encode(['date_from', 'date_to']),
                'permission_key' => 'report.read',
                'organization_scope_allowed' => false,
                'admin_only' => false,
            ],
        ];

        foreach ($definitions as &$def) {
            $def['created_at'] = $now;
            $def['updated_at'] = $now;
        }
        unset($def);

        DB::table('report_definitions')->upsert(
            $definitions,
            ['code'],
            ['name_ar', 'name_en', 'description_ar', 'description_en', 'report_family',
                'filter_schema', 'permission_key', 'organization_scope_allowed', 'admin_only', 'updated_at'],
        );
    }
}
