<?php

declare(strict_types=1);

namespace Modules\Students\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Modules\Students\Database\Factories\GuardianProfileFactory;
use Modules\Students\Enums\GuardianLifecycleStatus;

/**
 * Guardian identity and role record.
 *
 * One-to-one with Person (unique index on person_id). Creating a GuardianProfile
 * NEVER creates a GuardianAccount automatically.
 *
 * guardian_account_id is a plain integer cross-module reference to the Accounts
 * module's guardian_accounts table; no DB-level FK constraint.
 *
 * Portal access for a guardian requires active, verified, portal_eligible
 * GuardianStudentRelationship records — not merely a linked account.
 */
final class GuardianProfile extends Model
{
    /** @use HasFactory<GuardianProfileFactory> */
    use HasFactory;

    /**
     * guardian_code is excluded from $fillable; generated by CreateGuardianProfile.
     *
     * @var list<string>
     */
    protected $fillable = [
        'person_id',
        'lifecycle_status',
        'guardian_account_id',
    ];

    /** @var array<string, string> */
    protected $casts = [
        'lifecycle_status' => GuardianLifecycleStatus::class,
    ];

    /** @return HasMany<GuardianStudentRelationship, $this> */
    public function studentRelationships(): HasMany
    {
        return $this->hasMany(GuardianStudentRelationship::class);
    }

    /**
     * Portal-eligible relationships for this guardian.
     * Requires: verified + portal_eligible = true + not ended.
     *
     * @return HasMany<GuardianStudentRelationship, $this>
     */
    public function portalEligibleRelationships(): HasMany
    {
        return $this->hasMany(GuardianStudentRelationship::class)
            ->where('verification_status', 'verified')
            ->where('portal_eligible', true)
            ->where(fn ($q) => $q->whereNull('ends_on')->orWhere('ends_on', '>=', now()->toDateString()));
    }

    public function isActive(): bool
    {
        return $this->lifecycle_status === GuardianLifecycleStatus::Active;
    }
}
