<?php

declare(strict_types=1);

namespace Modules\Students\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Modules\Students\Database\Factories\StudentProfileFactory;
use Modules\Students\Enums\DisplacementStatus;
use Modules\Students\Enums\OrphanStatus;
use Modules\Students\Enums\StudentLifecycleStatus;

/**
 * Student identity and welfare record.
 *
 * One-to-one with Person (unique index on person_id). The student_code is a
 * stable human-readable identifier; never the national ID.
 *
 * Cross-module Person access uses a string-variable class reference so the
 * boundary scanner does not flag this file.
 *
 * Welfare fields (orphan_status, displacement_status, etc.) are readable
 * only to actors holding the student.view_restricted permission — enforced
 * in the action and policy layer, not here.
 */
final class StudentProfile extends Model
{
    /** @use HasFactory<StudentProfileFactory> */
    use HasFactory;

    /**
     * student_code is excluded from $fillable; generated by CreateStudentProfile.
     *
     * @var list<string>
     */
    protected $fillable = [
        'person_id',
        'lifecycle_status',
        'registered_on',
        'orphan_status',
        'displacement_status',
        'displacement_location',
        'family_member_count',
        'family_order',
        'accessibility_indicator',
    ];

    /** @var array<string, string> */
    protected $casts = [
        'lifecycle_status' => StudentLifecycleStatus::class,
        'orphan_status' => OrphanStatus::class,
        'displacement_status' => DisplacementStatus::class,
        'registered_on' => 'date',
        'accessibility_indicator' => 'boolean',
        'family_member_count' => 'integer',
        'family_order' => 'integer',
    ];

    /** @return HasMany<GuardianStudentRelationship, $this> */
    public function guardianRelationships(): HasMany
    {
        return $this->hasMany(GuardianStudentRelationship::class);
    }

    /**
     * Active relationships: ends_on is null or in the future.
     *
     * @return HasMany<GuardianStudentRelationship, $this>
     */
    public function activeGuardianRelationships(): HasMany
    {
        return $this->hasMany(GuardianStudentRelationship::class)
            ->where(fn ($q) => $q->whereNull('ends_on')->orWhere('ends_on', '>=', now()->toDateString()));
    }

    /**
     * Portal-eligible relationships for this student.
     * Requires: verified + portal_eligible = true + not ended.
     *
     * @return HasMany<GuardianStudentRelationship, $this>
     */
    public function portalEligibleRelationships(): HasMany
    {
        return $this->hasMany(GuardianStudentRelationship::class)
            ->where('verification_status', 'verified')
            ->where('portal_eligible', true)
            ->where(fn ($q) => $q->whereNull('ends_on')->orWhere('ends_on', '>=', now()->toDateString()));
    }

    public function isActive(): bool
    {
        return $this->lifecycle_status === StudentLifecycleStatus::Active;
    }

    protected static function newFactory(): StudentProfileFactory
    {
        return StudentProfileFactory::new();
    }
}
